# Generated by Django 4.2 on 2023-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankerApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup", name="email", field=models.CharField(max_length=100),
        ),
    ]
