# Generated by Django 4.2 on 2023-04-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rankerApp", "0003_alter_signup_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="signup", name="phone",),
    ]
