# Generated by Django 4.2 on 2023-04-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rankerApp", "0004_remove_signup_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup", old_name="name", new_name="username",
        ),
    ]
